[font]
normal = { family = "Comic Code", style = "Regular" }
bold = { family = "Comic Code", style = "Bold" }
italic = { family = "Comic Code", style = "Italic" }
bold_italic = { family = "Comic Code", style = "Bold Italic" }
size = 12

[terminal]
shell = "/usr/bin/fish"
