font=Comic Code:size=16
use-bold=yes
placeholder="program name"
lines=5
enable-mouse=no

[colors]
background=181616ff
text=8a9a7bff
prompt=737c73ff
placeholder=737c73ff
input=8a9a7bff
# match=cb4b16ff
selection=282727ff
selection-text=98bb6cff
selection-match=ff9e3bff
border=abababff

[border]
width=2
